package com.selenium;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.github.bonigarcia.wdm.WebDriverManager;

/**
 * Automated test for filling out the Contact form on https://chamilo.org/en/contact/
 */
public class ContactPageTest {

    private static final String CONTACT_URL = "https://chamilo.org/en/contact/";

    // Automated test data
    private static final String TEST_NAME = "[AUTOMATED TEST] Do Not Reply";
    private static final String TEST_EMAIL = "automated.test@noreply.example.com";
    private static final String TEST_SUBJECT = "[AUTOMATED] This is an automated test message - Please ignore";
    private static final String TEST_MESSAGE = "This is an automated message generated by a Selenium test script. "
            + "Please do not reply to this message. "
            + "This form submission is part of an automated testing process to verify the contact form functionality. "
            + "No action is required on your part. Thank you for your understanding.";

    private WebDriver driver;
    private WebDriverWait wait;

    @BeforeClass
    public void setUp() {
        WebDriverManager.chromedriver().setup();

        ChromeOptions options = new ChromeOptions();
        // Use Brave browser
        options.setBinary(resolveBraveBinary());
        options.addArguments(
                "--disable-notifications",
                "--start-maximized",
                "--disable-infobars",
                "--disable-extensions");

        driver = new ChromeDriver(options);
        wait = new WebDriverWait(driver, Duration.ofSeconds(15));
    }

    @AfterClass(alwaysRun = true)
    public void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }

    @Test(description = "Fill contact form with automated test data")
    public void testFillContactForm() throws InterruptedException {
        // Navigate to the contact page
        driver.get(CONTACT_URL);
        acceptCookiesIfPresent();

        // Wait for the form to be visible
        WebElement contactForm = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("form.wpcf7-form")));
        Assert.assertTrue(contactForm.isDisplayed(), "Contact form should be visible");

        // Fill in the Name field
        WebElement nameField = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[name='your-name']")));
        scrollIntoView(nameField);
        nameField.clear();
        nameField.sendKeys(TEST_NAME);
        System.out.println("✓ Filled Name field with: " + TEST_NAME);

        // Fill in the Email field
        WebElement emailField = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[name='your-email']")));
        scrollIntoView(emailField);
        emailField.clear();
        emailField.sendKeys(TEST_EMAIL);
        System.out.println("✓ Filled Email field with: " + TEST_EMAIL);

        // Fill in the Subject field
        WebElement subjectField = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[name='your-subject']")));
        scrollIntoView(subjectField);
        subjectField.clear();
        subjectField.sendKeys(TEST_SUBJECT);
        System.out.println("✓ Filled Subject field with: " + TEST_SUBJECT);

        // Fill in the Message/Tell Us field
        WebElement messageField = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("textarea[name='your-message']")));
        scrollIntoView(messageField);
        messageField.clear();
        messageField.sendKeys(TEST_MESSAGE);
        System.out.println("✓ Filled Message field");

        // Check the privacy policy checkbox - try multiple selectors
        WebElement privacyCheckbox = findPrivacyCheckbox();
        if (privacyCheckbox != null) {
            scrollIntoView(privacyCheckbox);
            
            // Click the checkbox using JavaScript if it's not directly clickable
            if (!privacyCheckbox.isSelected()) {
                try {
                    privacyCheckbox.click();
                } catch (Exception e) {
                    // If direct click fails, use JavaScript
                    ((JavascriptExecutor) driver).executeScript("arguments[0].click();", privacyCheckbox);
                }
            }
            System.out.println("✓ Checked privacy policy checkbox");
        } else {
            System.out.println("⚠ Privacy checkbox not found - may not exist on this page version");
        }

        // Verify all fields are filled
        Assert.assertEquals(nameField.getAttribute("value"), TEST_NAME, "Name field should contain test data");
        Assert.assertEquals(emailField.getAttribute("value"), TEST_EMAIL, "Email field should contain test data");
        Assert.assertEquals(subjectField.getAttribute("value"), TEST_SUBJECT, "Subject field should contain test data");
        Assert.assertEquals(messageField.getAttribute("value"), TEST_MESSAGE, "Message field should contain test data");

        System.out.println("\n========================================");
        System.out.println("✓ Contact form filled successfully!");
        System.out.println("========================================");
        System.out.println("Name: " + TEST_NAME);
        System.out.println("Email: " + TEST_EMAIL);
        System.out.println("Subject: " + TEST_SUBJECT);
        System.out.println("Message: " + TEST_MESSAGE.substring(0, 50) + "...");
        System.out.println("Privacy Policy: Accepted");
        System.out.println("========================================");
        
        // Note: We intentionally do NOT submit the form to avoid spam
        // If you need to test submission, uncomment the following:
        // WebElement submitButton = wait.until(
        //         ExpectedConditions.elementToBeClickable(By.cssSelector("input[type='submit']")));
        // submitButton.click();

        // Wait a moment to see the filled form
        Thread.sleep(3000);
    }

    @Test(description = "Verify contact form fields are present and accessible")
    public void testContactFormFieldsExist() {
        driver.get(CONTACT_URL);
        acceptCookiesIfPresent();

        // Verify Name field exists
        WebElement nameField = wait.until(
                ExpectedConditions.presenceOfElementLocated(By.cssSelector("input[name='your-name']")));
        Assert.assertTrue(nameField.isDisplayed(), "Name field should be present");

        // Verify Email field exists
        WebElement emailField = wait.until(
                ExpectedConditions.presenceOfElementLocated(By.cssSelector("input[name='your-email']")));
        Assert.assertTrue(emailField.isDisplayed(), "Email field should be present");

        // Verify Subject field exists
        WebElement subjectField = wait.until(
                ExpectedConditions.presenceOfElementLocated(By.cssSelector("input[name='your-subject']")));
        Assert.assertTrue(subjectField.isDisplayed(), "Subject field should be present");

        // Verify Message field exists
        WebElement messageField = wait.until(
                ExpectedConditions.presenceOfElementLocated(By.cssSelector("textarea[name='your-message']")));
        Assert.assertTrue(messageField.isDisplayed(), "Message/Tell Us field should be present");

        // Verify Privacy checkbox exists (try multiple selectors)
        WebElement privacyCheckbox = findPrivacyCheckbox();
        // Privacy checkbox is optional - some page versions may not have it
        if (privacyCheckbox != null) {
            System.out.println("✓ Privacy policy checkbox found");
        } else {
            System.out.println("⚠ Privacy checkbox not found - may not exist on this page version");
        }

        System.out.println("✓ All main contact form fields are present and accessible");
    }

    /**
     * Helper method to accept cookies if a cookie consent banner is present
     */
    private void acceptCookiesIfPresent() {
        List<By> cookieLocators = List.of(
                By.cssSelector("a.cc-dismiss"),
                By.cssSelector("button#wt-cli-accept-btn"),
                By.xpath("//button[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'i agree')]"),
                By.xpath("//a[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'i agree')]"),
                By.xpath("//button[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'accept')]"));

        for (By locator : cookieLocators) {
            try {
                WebElement button = new WebDriverWait(driver, Duration.ofSeconds(3))
                        .until(ExpectedConditions.elementToBeClickable(locator));
                button.click();
                System.out.println("✓ Accepted cookies");
                return;
            } catch (Exception ignored) {
                // Try next locator
            }
        }
    }

    /**
     * Helper method to find the privacy checkbox with multiple possible selectors
     */
    private WebElement findPrivacyCheckbox() {
        List<By> checkboxLocators = List.of(
                By.cssSelector("input[name='acceptance-privacy']"),
                By.cssSelector("input[name='acceptance']"),
                By.cssSelector("input[type='checkbox'][name*='privacy']"),
                By.cssSelector("input[type='checkbox'][name*='acceptance']"),
                By.cssSelector(".wpcf7-acceptance input[type='checkbox']"),
                By.xpath("//input[@type='checkbox'][following-sibling::*[contains(text(), 'privacy')]]"),
                By.xpath("//span[contains(@class, 'acceptance')]//input[@type='checkbox']"),
                By.xpath("//input[@type='checkbox'][ancestor::*[contains(text(), 'privacy policy')]]"));

        for (By locator : checkboxLocators) {
            try {
                WebElement checkbox = new WebDriverWait(driver, Duration.ofSeconds(3))
                        .until(ExpectedConditions.presenceOfElementLocated(locator));
                if (checkbox != null) {
                    System.out.println("✓ Found privacy checkbox using: " + locator);
                    return checkbox;
                }
            } catch (Exception ignored) {
                // Try next locator
            }
        }
        return null;
    }

    /**
     * Helper method to scroll an element into view
     */
    private void scrollIntoView(WebElement element) {
        ((JavascriptExecutor) driver).executeScript(
                "arguments[0].scrollIntoView({behavior: 'smooth', block: 'center'});", element);
        try {
            Thread.sleep(300);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    /**
     * Resolve the Brave browser binary path by checking multiple common installation locations
     */
    private String resolveBraveBinary() {
        // 1. Check environment variable first (highest priority)
        String envPath = System.getenv("BRAVE_PATH");
        if (envPath != null && Files.exists(Path.of(envPath))) {
            System.out.println("✓ Using Brave from BRAVE_PATH env variable: " + envPath);
            return envPath;
        }

        // 2. Check system property
        String sysProp = System.getProperty("brave.binary");
        if (sysProp != null && Files.exists(Path.of(sysProp))) {
            System.out.println("✓ Using Brave from system property: " + sysProp);
            return sysProp;
        }

        // 3. Search common installation paths
        String userHome = System.getProperty("user.home");
        List<String> possiblePaths = List.of(
                // Windows - User installation (most common)
                userHome + "/AppData/Local/BraveSoftware/Brave-Browser/Application/brave.exe",
                // Windows - Program Files
                "C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe",
                "C:/Program Files (x86)/BraveSoftware/Brave-Browser/Application/brave.exe",
                // macOS
                "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser",
                userHome + "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser",
                // Linux - Common locations
                "/usr/bin/brave",
                "/usr/bin/brave-browser",
                "/snap/bin/brave",
                "/opt/brave.com/brave/brave",
                userHome + "/.local/bin/brave"
        );

        for (String path : possiblePaths) {
            if (Files.exists(Path.of(path))) {
                System.out.println("✓ Found Brave at: " + path);
                return path;
            }
        }

        // 4. If not found, throw helpful error
        throw new IllegalStateException(
                "Brave browser not found. Please either:\n" +
                "  1. Set BRAVE_PATH environment variable to your brave.exe location\n" +
                "  2. Set -Dbrave.binary=<path> system property\n" +
                "  3. Install Brave in a standard location\n" +
                "Searched paths: " + possiblePaths);
    }
}
