package com.selenium;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.github.bonigarcia.wdm.WebDriverManager;

/**
 * Automated test for filling out the Contact form on https://chamilo.org/en/contact/
 */
public class ContactPageTest {

    private static final String CONTACT_URL = "https://chamilo.org/en/contact/";

    // Automated test data
    private static final String TEST_NAME = "[AUTOMATED TEST] Do Not Reply";
    private static final String TEST_EMAIL = "automated.test@noreply.example.com";
    private static final String TEST_SUBJECT = "[AUTOMATED] This is an automated test message - Please ignore";
    private static final String TEST_MESSAGE = "This is an automated message generated by a Selenium test script. "
            + "Please do not reply to this message. "
            + "This form submission is part of an automated testing process to verify the contact form functionality. "
            + "No action is required on your part. Thank you for your understanding.";

    private WebDriver driver;
    private WebDriverWait wait;

    @BeforeClass
    public void setUp() {
        WebDriverManager.chromedriver().setup();

        ChromeOptions options = new ChromeOptions();
        // Use Brave browser
        options.setBinary(resolveBraveBinary());
        options.addArguments(
                "--disable-notifications",
                "--start-maximized",
                "--disable-infobars",
                "--disable-extensions",
                "--disable-gpu",
                "--no-sandbox");

        driver = new ChromeDriver(options);
        wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    }

    @AfterClass(alwaysRun = true)
    public void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }

    @Test(description = "Fill contact form with automated test data")
    public void testFillContactForm() throws InterruptedException {
        // Navigate to the contact page
        driver.get(CONTACT_URL);
        acceptCookiesIfPresent();

        // Wait for the form to be visible
        WebElement contactForm = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("form.wpcf7-form")));
        Assert.assertTrue(contactForm.isDisplayed(), "Contact form should be visible");

        // Fill in the Name field
        WebElement nameField = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[name='your-name']")));
        scrollIntoView(nameField);
        nameField.clear();
        nameField.sendKeys(TEST_NAME);
        System.out.println("✓ Filled Name field with: " + TEST_NAME);

        // Fill in the Email field
        WebElement emailField = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[name='your-email']")));
        scrollIntoView(emailField);
        emailField.clear();
        emailField.sendKeys(TEST_EMAIL);
        System.out.println("✓ Filled Email field with: " + TEST_EMAIL);

        // Fill in the Subject field
        WebElement subjectField = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[name='your-subject']")));
        scrollIntoView(subjectField);
        subjectField.clear();
        subjectField.sendKeys(TEST_SUBJECT);
        System.out.println("✓ Filled Subject field with: " + TEST_SUBJECT);

        // Fill in the Message/Tell Us field
        WebElement messageField = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("textarea[name='your-message']")));
        scrollIntoView(messageField);
        messageField.clear();
        messageField.sendKeys(TEST_MESSAGE);
        System.out.println("✓ Filled Message field");

        // Check the privacy policy checkbox - try multiple selectors
        WebElement privacyCheckbox = findPrivacyCheckbox();
        if (privacyCheckbox != null) {
            scrollIntoView(privacyCheckbox);
            
            // Click the checkbox using JavaScript if it's not directly clickable
            if (!privacyCheckbox.isSelected()) {
                try {
                    privacyCheckbox.click();
                } catch (Exception e) {
                    // If direct click fails, use JavaScript
                    ((JavascriptExecutor) driver).executeScript("arguments[0].click();", privacyCheckbox);
                }
            }
            System.out.println("✓ Checked privacy policy checkbox");
        } else {
            System.out.println("⚠ Privacy checkbox not found - may not exist on this page version");
        }

        // Verify all fields are filled
        Assert.assertEquals(nameField.getAttribute("value"), TEST_NAME, "Name field should contain test data");
        Assert.assertEquals(emailField.getAttribute("value"), TEST_EMAIL, "Email field should contain test data");
        Assert.assertEquals(subjectField.getAttribute("value"), TEST_SUBJECT, "Subject field should contain test data");
        Assert.assertEquals(messageField.getAttribute("value"), TEST_MESSAGE, "Message field should contain test data");

        System.out.println("\n========================================");
        System.out.println("✓ Contact form filled successfully!");
        System.out.println("========================================");
        System.out.println("Name: " + TEST_NAME);
        System.out.println("Email: " + TEST_EMAIL);
        System.out.println("Subject: " + TEST_SUBJECT);
        System.out.println("Message: " + TEST_MESSAGE.substring(0, 50) + "...");
        System.out.println("Privacy Policy: Accepted");
        System.out.println("========================================");
        
        // Note: We intentionally do NOT submit the form to avoid spam
        // If you need to test submission, uncomment the following:
        // WebElement submitButton = wait.until(
        //         ExpectedConditions.elementToBeClickable(By.cssSelector("input[type='submit']")));
        // submitButton.click();

        // Wait a moment to see the filled form
        Thread.sleep(500);
    }

    @Test(description = "Fill contact form then click Chamilo logo to navigate back to homepage")
    public void testFillFormThenNavigateToHomepageViaLogo() throws InterruptedException {
        // ========== STEP 1: Navigate to contact page ==========
        System.out.println("\n========================================");
        System.out.println("STEP 1: Navigating to Contact Page");
        System.out.println("========================================");
        
        driver.get(CONTACT_URL);
        acceptCookiesIfPresent();

        // Wait for the form to be visible
        WebElement contactForm = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("form.wpcf7-form")));
        Assert.assertTrue(contactForm.isDisplayed(), "Contact form should be visible");
        System.out.println("✓ Contact page loaded successfully");

        // ========== STEP 2: Fill in the contact form ==========
        System.out.println("\n========================================");
        System.out.println("STEP 2: Filling Contact Form");
        System.out.println("========================================");

        // Fill in the Name field
        WebElement nameField = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[name='your-name']")));
        scrollIntoView(nameField);
        nameField.clear();
        nameField.sendKeys(TEST_NAME);
        System.out.println("✓ Filled Name field with: " + TEST_NAME);

        // Fill in the Email field
        WebElement emailField = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[name='your-email']")));
        scrollIntoView(emailField);
        emailField.clear();
        emailField.sendKeys(TEST_EMAIL);
        System.out.println("✓ Filled Email field with: " + TEST_EMAIL);

        // Fill in the Subject field
        WebElement subjectField = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[name='your-subject']")));
        scrollIntoView(subjectField);
        subjectField.clear();
        subjectField.sendKeys(TEST_SUBJECT);
        System.out.println("✓ Filled Subject field with: " + TEST_SUBJECT);

        // Fill in the Message/Tell Us field
        WebElement messageField = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("textarea[name='your-message']")));
        scrollIntoView(messageField);
        messageField.clear();
        messageField.sendKeys(TEST_MESSAGE);
        System.out.println("✓ Filled Message field");

        // Check the privacy policy checkbox if present
        WebElement privacyCheckbox = findPrivacyCheckbox();
        if (privacyCheckbox != null) {
            scrollIntoView(privacyCheckbox);
            if (!privacyCheckbox.isSelected()) {
                try {
                    privacyCheckbox.click();
                } catch (Exception e) {
                    ((JavascriptExecutor) driver).executeScript("arguments[0].click();", privacyCheckbox);
                }
            }
            System.out.println("✓ Checked privacy policy checkbox");
        }

        // Verify all fields are filled
        Assert.assertEquals(nameField.getAttribute("value"), TEST_NAME, "Name field should contain test data");
        Assert.assertEquals(emailField.getAttribute("value"), TEST_EMAIL, "Email field should contain test data");
        Assert.assertEquals(subjectField.getAttribute("value"), TEST_SUBJECT, "Subject field should contain test data");
        Assert.assertEquals(messageField.getAttribute("value"), TEST_MESSAGE, "Message field should contain test data");

        System.out.println("\n✓ All form fields filled successfully!");
        
        // Wait a moment to see the filled form
        Thread.sleep(300);

        // ========== STEP 3: Click logo to navigate back to homepage ==========
        System.out.println("\n========================================");
        System.out.println("STEP 3: Clicking Logo to Go Back Home");
        System.out.println("========================================");

        // Find the Chamilo logo in the navbar
        WebElement logo = findChamiloLogo();
        Assert.assertNotNull(logo, "Chamilo logo should be present in the navbar");

        // Get the current URL before clicking
        String currentUrl = driver.getCurrentUrl();
        System.out.println("Current URL (Contact Page): " + currentUrl);

        // Scroll to top to make logo visible and click it
        ((JavascriptExecutor) driver).executeScript("window.scrollTo(0, 0);");
        Thread.sleep(200);
        
        scrollIntoView(logo);
        try {
            logo.click();
        } catch (Exception e) {
            // If direct click fails, use JavaScript
            ((JavascriptExecutor) driver).executeScript("arguments[0].click();", logo);
        }
        System.out.println("✓ Clicked on Chamilo logo");

        // Wait for navigation to complete
        wait.until(ExpectedConditions.not(ExpectedConditions.urlToBe(currentUrl)));

        // ========== STEP 4: Verify homepage ==========
        System.out.println("\n========================================");
        System.out.println("STEP 4: Verifying Homepage Navigation");
        System.out.println("========================================");

        String newUrl = driver.getCurrentUrl();
        System.out.println("New URL (Homepage): " + newUrl);

        // The homepage should be https://chamilo.org/en/ or https://chamilo.org/
        boolean isHomepage = newUrl.equals("https://chamilo.org/en/") 
                || newUrl.equals("https://chamilo.org/") 
                || newUrl.matches("https://chamilo\\.org(/en)?/?");
        
        Assert.assertTrue(isHomepage, 
                "Clicking logo should navigate to homepage. Expected homepage URL but got: " + newUrl);

        // Wait to see the homepage
        Thread.sleep(300);

        // ========== STEP 5: Navigate back to Contact Page ==========
        System.out.println("\n========================================");
        System.out.println("STEP 5: Navigating Back to Contact Page");
        System.out.println("========================================");

        // Navigate back to contact page
        driver.get(CONTACT_URL);
        
        // Wait for the contact form to be visible again
        WebElement contactFormAgain = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("form.wpcf7-form")));
        Assert.assertTrue(contactFormAgain.isDisplayed(), "Contact form should be visible after navigating back");
        
        String finalUrl = driver.getCurrentUrl();
        System.out.println("✓ Successfully navigated back to Contact Page");
        System.out.println("Final URL: " + finalUrl);
        
        // Verify we're on the contact page
        Assert.assertTrue(finalUrl.contains("/contact"), 
                "Should be back on contact page. Current URL: " + finalUrl);

        // Wait to see the contact page
        Thread.sleep(300);

        // ========== SUMMARY ==========
        System.out.println("\n========================================");
        System.out.println("✓ TEST COMPLETED SUCCESSFULLY!");
        System.out.println("========================================");
        System.out.println("Flow Summary:");
        System.out.println("  1. ✓ Navigated to Contact Page");
        System.out.println("  2. ✓ Filled all form fields:");
        System.out.println("       - Name: " + TEST_NAME);
        System.out.println("       - Email: " + TEST_EMAIL);
        System.out.println("       - Subject: " + TEST_SUBJECT);
        System.out.println("       - Message: [filled]");
        System.out.println("       - Privacy: [accepted]");
        System.out.println("  3. ✓ Clicked Chamilo logo in navbar");
        System.out.println("  4. ✓ Successfully navigated to homepage");
        System.out.println("       From: " + currentUrl);
        System.out.println("       To:   " + newUrl);
        System.out.println("  5. ✓ Navigated back to Contact Page");
        System.out.println("       Final URL: " + finalUrl);
        System.out.println("========================================");
    }

    @Test(description = "Verify contact form fields are present and accessible")
    public void testContactFormFieldsExist() {
        driver.get(CONTACT_URL);
        acceptCookiesIfPresent();

        // Verify Name field exists
        WebElement nameField = wait.until(
                ExpectedConditions.presenceOfElementLocated(By.cssSelector("input[name='your-name']")));
        Assert.assertTrue(nameField.isDisplayed(), "Name field should be present");

        // Verify Email field exists
        WebElement emailField = wait.until(
                ExpectedConditions.presenceOfElementLocated(By.cssSelector("input[name='your-email']")));
        Assert.assertTrue(emailField.isDisplayed(), "Email field should be present");

        // Verify Subject field exists
        WebElement subjectField = wait.until(
                ExpectedConditions.presenceOfElementLocated(By.cssSelector("input[name='your-subject']")));
        Assert.assertTrue(subjectField.isDisplayed(), "Subject field should be present");

        // Verify Message field exists
        WebElement messageField = wait.until(
                ExpectedConditions.presenceOfElementLocated(By.cssSelector("textarea[name='your-message']")));
        Assert.assertTrue(messageField.isDisplayed(), "Message/Tell Us field should be present");

        // Verify Privacy checkbox exists (try multiple selectors)
        WebElement privacyCheckbox = findPrivacyCheckbox();
        // Privacy checkbox is optional - some page versions may not have it
        if (privacyCheckbox != null) {
            System.out.println("✓ Privacy policy checkbox found");
        } else {
            System.out.println("⚠ Privacy checkbox not found - may not exist on this page version");
        }

        System.out.println("✓ All main contact form fields are present and accessible");
    }

    // ==================== PENGUJIAN BERDASARKAN CEKLIST.MD ====================

    @Test(description = "1. Pengujian Judul Halaman - Verifikasi judul 'Contact' ditampilkan dengan benar")
    public void testPageTitleDisplayed() {
        System.out.println("\n========================================");
        System.out.println("TEST: Pengujian Judul Halaman");
        System.out.println("========================================");

        driver.get(CONTACT_URL);
        acceptCookiesIfPresent();

        // Verifikasi halaman judul "Contact" ditampilkan dengan benar di halaman
        WebElement pageTitle = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("h1, .entry-title, .page-title")));
        Assert.assertTrue(pageTitle.getText().toLowerCase().contains("contact"),
                "Page title should contain 'Contact'. Actual: " + pageTitle.getText());
        System.out.println("✓ Page title displayed: " + pageTitle.getText());

        // Verifikasi halaman judul terlihat di browser tab
        String browserTitle = driver.getTitle();
        Assert.assertTrue(browserTitle.toLowerCase().contains("contact"),
                "Browser tab title should contain 'Contact'. Actual: " + browserTitle);
        System.out.println("✓ Browser tab title: " + browserTitle);

        System.out.println("✓ Pengujian Judul Halaman PASSED");
    }

    @Test(description = "2. Pengujian Form Kontak - Verifikasi form labels dan input fields")
    public void testContactFormLabelsAndInputs() {
        System.out.println("\n========================================");
        System.out.println("TEST: Pengujian Form Kontak");
        System.out.println("========================================");

        driver.get(CONTACT_URL);
        acceptCookiesIfPresent();

        // Verifikasi contact form terlihat
        WebElement contactForm = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("form.wpcf7-form")));
        Assert.assertTrue(contactForm.isDisplayed(), "Contact form should be visible");
        System.out.println("✓ Contact form is visible");

        // Verifikasi form field labels clear dan visible
        String pageSource = driver.getPageSource().toLowerCase();
        Assert.assertTrue(pageSource.contains("name") || pageSource.contains("nombre"),
                "Name label should be visible");
        System.out.println("✓ Name label is visible");
        
        Assert.assertTrue(pageSource.contains("email") || pageSource.contains("correo"),
                "Email label should be visible");
        System.out.println("✓ Email label is visible");
        
        Assert.assertTrue(pageSource.contains("subject") || pageSource.contains("asunto"),
                "Subject label should be visible");
        System.out.println("✓ Subject label is visible");

        // Verifikasi form accepts text input in semua fields
        WebElement nameField = driver.findElement(By.cssSelector("input[name='your-name']"));
        nameField.clear();
        nameField.sendKeys("Test Input Name");
        Assert.assertEquals(nameField.getAttribute("value"), "Test Input Name",
                "Name field should accept text input");
        System.out.println("✓ Name field accepts text input");

        WebElement emailField = driver.findElement(By.cssSelector("input[name='your-email']"));
        emailField.clear();
        emailField.sendKeys("test@example.com");
        Assert.assertEquals(emailField.getAttribute("value"), "test@example.com",
                "Email field should accept text input");
        System.out.println("✓ Email field accepts text input");

        WebElement subjectField = driver.findElement(By.cssSelector("input[name='your-subject']"));
        subjectField.clear();
        subjectField.sendKeys("Test Subject");
        Assert.assertEquals(subjectField.getAttribute("value"), "Test Subject",
                "Subject field should accept text input");
        System.out.println("✓ Subject field accepts text input");

        WebElement messageField = driver.findElement(By.cssSelector("textarea[name='your-message']"));
        messageField.clear();
        messageField.sendKeys("Test Message Content");
        Assert.assertEquals(messageField.getAttribute("value"), "Test Message Content",
                "Message field should accept text input");
        System.out.println("✓ Message field accepts text input");

        System.out.println("✓ Pengujian Form Kontak PASSED");
    }

    @Test(description = "3. Pengujian Checkbox Kebijakan Privasi")
    public void testPrivacyPolicyCheckbox() throws InterruptedException {
        System.out.println("\n========================================");
        System.out.println("TEST: Pengujian Checkbox Kebijakan Privasi");
        System.out.println("========================================");

        driver.get(CONTACT_URL);
        acceptCookiesIfPresent();

        // Verifikasi privacy policy acceptance checkbox ada
        WebElement privacyCheckbox = findPrivacyCheckbox();
        Assert.assertNotNull(privacyCheckbox, "Privacy policy checkbox should exist");
        System.out.println("✓ Privacy policy checkbox exists");

        // Verifikasi checkbox text "I have read and I accept the privacy policy" ditampilkan
        String pageSource = driver.getPageSource();
        boolean hasPrivacyText = pageSource.contains("I have read") && pageSource.contains("privacy policy");
        Assert.assertTrue(hasPrivacyText, 
                "Checkbox text 'I have read and I accept the privacy policy' should be displayed");
        System.out.println("✓ Privacy policy checkbox text is displayed correctly");

        // Verifikasi "privacy policy" link within checkbox text dapat diklik
        WebElement privacyLink = null;
        try {
            privacyLink = driver.findElement(By.xpath("//a[contains(@href, 'aviso-legal')]"));
        } catch (Exception e) {
            privacyLink = driver.findElement(By.xpath("//a[contains(text(), 'privacy policy')]"));
        }
        Assert.assertNotNull(privacyLink, "Privacy policy link should exist");
        Assert.assertTrue(privacyLink.isDisplayed(), "Privacy policy link should be visible");
        System.out.println("✓ Privacy policy link is clickable");

        // Verifikasi link href mengarahkan ke https://chamilo.org/en/aviso-legal/
        String linkHref = privacyLink.getAttribute("href");
        Assert.assertTrue(linkHref.contains("aviso-legal"),
                "Privacy policy link should point to aviso-legal page. Actual: " + linkHref);
        System.out.println("✓ Privacy policy link points to: " + linkHref);

        // Verifikasi checkbox can be checked dan unchecked
        scrollIntoView(privacyCheckbox);
        boolean initialState = privacyCheckbox.isSelected();
        System.out.println("  Initial checkbox state: " + (initialState ? "checked" : "unchecked"));

        // Check the checkbox
        if (!privacyCheckbox.isSelected()) {
            try {
                privacyCheckbox.click();
            } catch (Exception e) {
                ((JavascriptExecutor) driver).executeScript("arguments[0].click();", privacyCheckbox);
            }
        }
        Thread.sleep(200);
        Assert.assertTrue(privacyCheckbox.isSelected(), "Checkbox should be checked after clicking");
        System.out.println("✓ Checkbox can be checked");

        // Uncheck the checkbox
        try {
            privacyCheckbox.click();
        } catch (Exception e) {
            ((JavascriptExecutor) driver).executeScript("arguments[0].click();", privacyCheckbox);
        }
        Thread.sleep(200);
        Assert.assertFalse(privacyCheckbox.isSelected(), "Checkbox should be unchecked after clicking again");
        System.out.println("✓ Checkbox can be unchecked");

        System.out.println("✓ Pengujian Checkbox Kebijakan Privasi PASSED");
    }

    @Test(description = "4. Privacy Information Section - Verifikasi alamat dan informasi privasi")
    public void testPrivacyInformationSection() {
        System.out.println("\n========================================");
        System.out.println("TEST: Privacy Information Pengujian Seksi");
        System.out.println("========================================");

        driver.get(CONTACT_URL);
        acceptCookiesIfPresent();

        String pageSource = driver.getPageSource();

        // Verifikasi "Data privacy responsible" information
        // Organization: "Asociación Chamilo"
        Assert.assertTrue(pageSource.contains("Asociación Chamilo"),
                "Organization 'Asociación Chamilo' should be displayed");
        System.out.println("✓ Organization found: Asociación Chamilo");

        // Address components
        Assert.assertTrue(pageSource.contains("Urb. As Rozas 24"),
                "Street address 'Urb. As Rozas 24' should be displayed");
        System.out.println("✓ Street address found: Urb. As Rozas 24");

        Assert.assertTrue(pageSource.contains("27150"),
                "Postal code '27150' should be displayed");
        System.out.println("✓ Postal code found: 27150");

        Assert.assertTrue(pageSource.contains("Outeiro de Rei"),
                "City 'Outeiro de Rei' should be displayed");
        System.out.println("✓ City found: Outeiro de Rei");

        Assert.assertTrue(pageSource.contains("Lugo"),
                "Province 'Lugo' should be displayed");
        System.out.println("✓ Province found: Lugo");

        Assert.assertTrue(pageSource.contains("Spain"),
                "Country 'Spain' should be displayed");
        System.out.println("✓ Country found: Spain");

        // Verifikasi "Objective" section
        Assert.assertTrue(pageSource.contains("Objective") || pageSource.contains("Answer your questions"),
                "Objective section should be displayed");
        System.out.println("✓ Objective section is displayed");

        // Verifikasi "Legitimation" section
        Assert.assertTrue(pageSource.contains("Legitimation") || pageSource.contains("User consent"),
                "Legitimation section should be displayed");
        System.out.println("✓ Legitimation section is displayed");

        // Verifikasi "Rights" section
        Assert.assertTrue(pageSource.contains("Rights") || pageSource.contains("access, correction, removal"),
                "Rights section should be displayed");
        System.out.println("✓ Rights section is displayed");

        System.out.println("\n========================================");
        System.out.println("Full Address Verified:");
        System.out.println("  Asociación Chamilo");
        System.out.println("  Urb. As Rozas 24 - Matela - 27150");
        System.out.println("  Outeiro de Rei - Lugo - Spain");
        System.out.println("========================================");

        System.out.println("✓ Privacy Information Pengujian Seksi PASSED");
    }

    @Test(description = "5. Pengujian SEND Button")
    public void testSendButton() throws InterruptedException {
        System.out.println("\n========================================");
        System.out.println("TEST: Pengujian SEND Button");
        System.out.println("========================================");

        driver.get(CONTACT_URL);
        acceptCookiesIfPresent();

        // Wait for form to be visible first
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("form.wpcf7-form")));

        // Verifikasi "SEND" button terlihat - try multiple selectors
        WebElement sendButton = findSendButton();
        Assert.assertNotNull(sendButton, "SEND button should exist");
        
        scrollIntoView(sendButton);
        Thread.sleep(200);
        
        // Check if visible using JavaScript (more reliable)
        Boolean isVisible = (Boolean) ((JavascriptExecutor) driver)
                .executeScript("var elem = arguments[0]; " +
                        "var style = window.getComputedStyle(elem); " +
                        "return style.display !== 'none' && style.visibility !== 'hidden' && elem.offsetHeight > 0;", sendButton);
        
        Assert.assertTrue(isVisible != null && isVisible, "SEND button should be visible");
        System.out.println("✓ SEND button is visible");

        // Verifikasi button text
        String buttonValue = sendButton.getAttribute("value");
        if (buttonValue == null || buttonValue.isEmpty()) {
            buttonValue = sendButton.getText();
        }
        System.out.println("✓ SEND button text: " + buttonValue);

        // Verifikasi button exists as submit type (may be disabled until form is filled)
        String buttonType = sendButton.getAttribute("type");
        Assert.assertEquals(buttonType, "submit", "Button should be of type 'submit'");
        System.out.println("✓ SEND button is of type 'submit'");
        
        // Check button state (may be disabled for validation)
        boolean isEnabled = sendButton.isEnabled();
        System.out.println("✓ SEND button enabled state: " + isEnabled + " (may be disabled until form is valid)");

        System.out.println("✓ Pengujian SEND Button PASSED");
    }

    @Test(description = "6. Pengujian Gambar Kontak")
    public void testContactImage() {
        System.out.println("\n========================================");
        System.out.println("TEST: Pengujian Gambar Kontak");
        System.out.println("========================================");

        driver.get(CONTACT_URL);
        acceptCookiesIfPresent();

        // Verifikasi contact/mail image dimuat dengan benar
        List<WebElement> images = driver.findElements(By.cssSelector("img[src*='mail'], img[alt*='mail'], img[alt*='contact'], img[src*='contact']"));
        
        if (images.isEmpty()) {
            // Try to find any image in the content area
            images = driver.findElements(By.cssSelector(".entry-content img, .page-content img, article img"));
        }

        boolean imageFound = false;
        for (WebElement img : images) {
            if (img.isDisplayed()) {
                String src = img.getAttribute("src");
                String alt = img.getAttribute("alt");
                
                // Verify image loaded correctly (naturalWidth > 0 means image loaded)
                Long naturalWidth = (Long) ((JavascriptExecutor) driver)
                        .executeScript("return arguments[0].naturalWidth;", img);
                
                if (naturalWidth != null && naturalWidth > 0) {
                    imageFound = true;
                    System.out.println("✓ Contact image found and loaded correctly");
                    System.out.println("  - Source: " + src);
                    System.out.println("  - Alt text: " + (alt != null ? alt : "none"));
                    System.out.println("  - Natural width: " + naturalWidth + "px");
                    break;
                }
            }
        }

        // If no specific contact image found, just verify no broken images
        if (!imageFound) {
            List<WebElement> allImages = driver.findElements(By.tagName("img"));
            int brokenImages = 0;
            for (WebElement img : allImages) {
                Long naturalWidth = (Long) ((JavascriptExecutor) driver)
                        .executeScript("return arguments[0].naturalWidth;", img);
                if (naturalWidth == null || naturalWidth == 0) {
                    brokenImages++;
                    System.out.println("⚠ Broken image found: " + img.getAttribute("src"));
                }
            }
            Assert.assertEquals(brokenImages, 0, "There should be no broken images on the page");
            System.out.println("✓ No broken images found on the page");
        }

        System.out.println("✓ Pengujian Gambar Kontak PASSED");
    }

    @Test(description = "7. Pengujian Form Validation - Required fields")
    public void testFormValidationRequiredFields() throws InterruptedException {
        System.out.println("\n========================================");
        System.out.println("TEST: Pengujian Form Validation");
        System.out.println("========================================");

        driver.get(CONTACT_URL);
        acceptCookiesIfPresent();

        // Wait for form to be visible first
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("form.wpcf7-form")));

        // Find send button using helper method
        WebElement sendButton = findSendButton();
        Assert.assertNotNull(sendButton, "SEND button should exist for form validation test");
        scrollIntoView(sendButton);
        Thread.sleep(200);

        // Check for validation - either HTML5 validation or form validation message
        // Check if fields have 'required' attribute
        WebElement nameField = driver.findElement(By.cssSelector("input[name='your-name']"));
        WebElement emailField = driver.findElement(By.cssSelector("input[name='your-email']"));
        
        // Check for wpcf7 validation response or HTML5 validation
        String pageSource = driver.getPageSource();
        boolean hasValidation = pageSource.contains("wpcf7-not-valid") 
                || pageSource.contains("required")
                || pageSource.contains("validation")
                || nameField.getAttribute("required") != null
                || nameField.getAttribute("aria-required") != null;

        System.out.println("✓ Form has validation for required fields: " + hasValidation);
        
        // Verify email field type is email (provides format validation)
        String emailType = emailField.getAttribute("type");
        Assert.assertEquals(emailType, "email", "Email field should have type 'email' for validation");
        System.out.println("✓ Email field type: " + emailType);
        
        // Verify submit button exists (may be disabled for form validation)
        String buttonType = sendButton.getAttribute("type");
        Assert.assertEquals(buttonType, "submit", "Submit button should be of type 'submit'");
        System.out.println("✓ Submit button exists and is type 'submit'");
        
        // Note: Button may be disabled until form is valid - this is expected behavior
        boolean isEnabled = sendButton.isEnabled();
        System.out.println("✓ Submit button enabled state: " + isEnabled + " (disabled = form validation active)");

        System.out.println("✓ Pengujian Form Validation PASSED");
    }

    @Test(description = "8. Pengujian Form Security - HTTPS")
    public void testFormSecurityHttps() {
        System.out.println("\n========================================");
        System.out.println("TEST: Pengujian Form Security");
        System.out.println("========================================");

        driver.get(CONTACT_URL);
        acceptCookiesIfPresent();

        // Verifikasi form submission secure (HTTPS)
        String currentUrl = driver.getCurrentUrl();
        Assert.assertTrue(currentUrl.startsWith("https://"),
                "Page should be served over HTTPS. Actual URL: " + currentUrl);
        System.out.println("✓ Page is served over HTTPS");

        // Check form action URL is also HTTPS
        WebElement form = driver.findElement(By.cssSelector("form.wpcf7-form"));
        String formAction = form.getAttribute("action");
        if (formAction != null && !formAction.isEmpty() && !formAction.startsWith("#")) {
            Assert.assertTrue(formAction.startsWith("https://") || formAction.startsWith("/"),
                    "Form action should use HTTPS. Actual: " + formAction);
            System.out.println("✓ Form action is secure: " + formAction);
        } else {
            System.out.println("✓ Form submits to same page (secure)");
        }

        System.out.println("✓ Pengujian Form Security PASSED");
    }

    /**
     * Helper method to accept cookies if a cookie consent banner is present
     */
    private void acceptCookiesIfPresent() {
        List<By> cookieLocators = List.of(
                By.cssSelector("a.cc-dismiss"),
                By.cssSelector("button#wt-cli-accept-btn"),
                By.xpath("//button[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'i agree')]"),
                By.xpath("//a[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'i agree')]"),
                By.xpath("//button[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'accept')]"));

        for (By locator : cookieLocators) {
            try {
                WebElement button = new WebDriverWait(driver, Duration.ofSeconds(3))
                        .until(ExpectedConditions.elementToBeClickable(locator));
                button.click();
                System.out.println("✓ Accepted cookies");
                return;
            } catch (Exception ignored) {
                // Try next locator
            }
        }
    }

    /**
     * Helper method to find the SEND/Submit button with multiple possible selectors
     */
    private WebElement findSendButton() {
        List<By> buttonLocators = List.of(
                By.cssSelector("form.wpcf7-form input[type='submit']"),
                By.cssSelector("form.wpcf7-form button[type='submit']"),
                By.cssSelector(".wpcf7-submit"),
                By.cssSelector("input.wpcf7-submit"),
                By.cssSelector("input[type='submit'][value*='Send']"),
                By.cssSelector("input[type='submit'][value*='SEND']"),
                By.cssSelector("input[type='submit'][value*='Enviar']"),
                By.xpath("//form[contains(@class, 'wpcf7')]//input[@type='submit']"),
                By.xpath("//input[@type='submit']"),
                By.xpath("//button[@type='submit']"),
                By.xpath("//input[contains(@class, 'submit')]"),
                By.xpath("//button[contains(text(), 'Send')]"),
                By.xpath("//button[contains(text(), 'SEND')]"));

        for (By locator : buttonLocators) {
            try {
                WebElement button = new WebDriverWait(driver, Duration.ofSeconds(3))
                        .until(ExpectedConditions.presenceOfElementLocated(locator));
                if (button != null) {
                    System.out.println("✓ Found SEND button using: " + locator);
                    return button;
                }
            } catch (Exception ignored) {
                // Try next locator
            }
        }
        return null;
    }

    /**
     * Helper method to find the Chamilo logo in the navbar with multiple possible selectors
     */
    private WebElement findChamiloLogo() {
        List<By> logoLocators = List.of(
                // Common navbar logo selectors
                By.cssSelector("header a.logo"),
                By.cssSelector("header .logo a"),
                By.cssSelector("header a img[alt*='Chamilo']"),
                By.cssSelector("header a img[alt*='chamilo']"),
                By.cssSelector("nav a.logo"),
                By.cssSelector(".navbar-brand"),
                By.cssSelector("a.navbar-brand"),
                By.cssSelector("header a[href='/']"),
                By.cssSelector("header a[href='/en/']"),
                By.cssSelector("header a[href='https://chamilo.org/']"),
                By.cssSelector("header a[href='https://chamilo.org/en/']"),
                By.cssSelector(".site-logo a"),
                By.cssSelector(".site-branding a"),
                By.cssSelector("#logo a"),
                By.cssSelector("a#logo"),
                By.xpath("//header//a[.//img[contains(@alt, 'Chamilo') or contains(@alt, 'chamilo') or contains(@alt, 'Logo')]]"),
                By.xpath("//header//a[contains(@class, 'logo')]"),
                By.xpath("//nav//a[.//img]"),
                By.xpath("//header//a[contains(@href, 'chamilo.org')][.//img]"),
                By.xpath("//a[contains(@class, 'custom-logo-link')]"),
                By.cssSelector("a.custom-logo-link"));

        for (By locator : logoLocators) {
            try {
                WebElement logo = new WebDriverWait(driver, Duration.ofSeconds(3))
                        .until(ExpectedConditions.presenceOfElementLocated(locator));
                if (logo != null && logo.isDisplayed()) {
                    System.out.println("✓ Found Chamilo logo using: " + locator);
                    return logo;
                }
            } catch (Exception ignored) {
                // Try next locator
            }
        }
        
        // Last resort: find any clickable element in header that looks like a logo
        try {
            WebElement headerLink = driver.findElement(By.cssSelector("header a:first-of-type"));
            if (headerLink != null) {
                System.out.println("✓ Found header link as fallback for logo");
                return headerLink;
            }
        } catch (Exception ignored) {
        }
        
        return null;
    }

    /**
     * Helper method to find the privacy checkbox with multiple possible selectors
     */
    private WebElement findPrivacyCheckbox() {
        List<By> checkboxLocators = List.of(
                By.cssSelector("input[name='acceptance-privacy']"),
                By.cssSelector("input[name='acceptance']"),
                By.cssSelector("input[type='checkbox'][name*='privacy']"),
                By.cssSelector("input[type='checkbox'][name*='acceptance']"),
                By.cssSelector(".wpcf7-acceptance input[type='checkbox']"),
                By.xpath("//input[@type='checkbox'][following-sibling::*[contains(text(), 'privacy')]]"),
                By.xpath("//span[contains(@class, 'acceptance')]//input[@type='checkbox']"),
                By.xpath("//input[@type='checkbox'][ancestor::*[contains(text(), 'privacy policy')]]"));

        for (By locator : checkboxLocators) {
            try {
                WebElement checkbox = new WebDriverWait(driver, Duration.ofSeconds(3))
                        .until(ExpectedConditions.presenceOfElementLocated(locator));
                if (checkbox != null) {
                    System.out.println("✓ Found privacy checkbox using: " + locator);
                    return checkbox;
                }
            } catch (Exception ignored) {
                // Try next locator
            }
        }
        return null;
    }

    /**
     * Helper method to scroll an element into view
     */
    private void scrollIntoView(WebElement element) {
        ((JavascriptExecutor) driver).executeScript(
                "arguments[0].scrollIntoView({behavior: 'instant', block: 'center'});", element);
        try {
            Thread.sleep(100);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    /**
     * Resolve the Brave browser binary path by checking multiple common installation locations
     */
    private String resolveBraveBinary() {
        // 1. Check environment variable first (highest priority)
        String envPath = System.getenv("BRAVE_PATH");
        if (envPath != null && Files.exists(Path.of(envPath))) {
            System.out.println("✓ Using Brave from BRAVE_PATH env variable: " + envPath);
            return envPath;
        }

        // 2. Check system property
        String sysProp = System.getProperty("brave.binary");
        if (sysProp != null && Files.exists(Path.of(sysProp))) {
            System.out.println("✓ Using Brave from system property: " + sysProp);
            return sysProp;
        }

        // 3. Search common installation paths
        String userHome = System.getProperty("user.home");
        List<String> possiblePaths = List.of(
                // Windows - User installation (most common)
                userHome + "/AppData/Local/BraveSoftware/Brave-Browser/Application/brave.exe",
                // Windows - Program Files
                "C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe",
                "C:/Program Files (x86)/BraveSoftware/Brave-Browser/Application/brave.exe",
                // macOS
                "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser",
                userHome + "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser",
                // Linux - Common locations
                "/usr/bin/brave",
                "/usr/bin/brave-browser",
                "/snap/bin/brave",
                "/opt/brave.com/brave/brave",
                userHome + "/.local/bin/brave"
        );

        for (String path : possiblePaths) {
            if (Files.exists(Path.of(path))) {
                System.out.println("✓ Found Brave at: " + path);
                return path;
            }
        }

        // 4. If not found, throw helpful error
        throw new IllegalStateException(
                "Brave browser not found. Please either:\n" +
                "  1. Set BRAVE_PATH environment variable to your brave.exe location\n" +
                "  2. Set -Dbrave.binary=<path> system property\n" +
                "  3. Install Brave in a standard location\n" +
                "Searched paths: " + possiblePaths);
    }
}
